service: product-service


custom:
  tableName: 'Products'
  bucketName: 'productsbucketfortesting'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - s3:PutObject
            - events:PutEvents  # Permission to publish events to EventBridge
            - events:DescribeEventBus  # Permission to describe EventBridge event bus
            - events:PutRule  # Permission to create/update EventBridge rule
            - events:PutTargets
            - lambda:InvokeFunction  # Permission to create/update targets for EventBridge rule
            
          Resource:
            - Fn::GetAtt: [ ProductsTable, Arn ]  # Replace with the ARN of the DynamoDB table
            - Fn::GetAtt: [ ProductBucket, Arn ]  # Replace with the ARN of the S3 bucket
            - '*'  # Allows all resources for EventBridge permissions

functions:
  createProduct:
    handler: lambdas/createProductHandler.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true
    environment:
     PRODUCTS_TABLE: ${self:custom.tableName}   
     PRODUCTS_BUCKET: ${self:custom.bucketName}    

  getProducts:
    handler: lambdas/getProductsHandler.getProducts
    events:
      - http:
          path: products
          method: get
          cors: true
    environment:
     PRODUCTS_TABLE: ${self:custom.tableName}
     PRODUCTS_BUCKET: ${self:custom.bucketName}       

  deleteProduct:
    handler: lambdas/deleteProductHandler.deleteProduct
    events:
      - http:
          path: products/{productId}
          method: delete
          cors: true
    environment:
     PRODUCTS_TABLE: ${self:custom.tableName}
     PRODUCTS_BUCKET: ${self:custom.bucketName}    
  
  convertToThumbnail:
    handler: lambdas/convertToThumbnail.convertToThumbnail
    events:
      - eventBridge:
          eventBus: default
          pattern:
            source:
              - 'custom.createProduct' 

resources:
  Resources:
    # MyApiGateway:
    #   Type: AWS::ApiGatewayV2::Api
    #   Properties:
    #     Name: MyApi
    ProductBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        CorsConfiguration:  # Add CORS configuration for the bucket
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
              AllowedOrigins:
                - "*"  # Replace with specific allowed origins if needed

    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

 

